<style>
    /*html, body {*/
        /*position: relative;*/
        /*height: 100%;*/
    /*}*/
    /*body {*/
        /*background: #000;*/
        /*font-family: Helvetica Neue, Helvetica, Arial, sans-serif;*/
        /*font-size: 14px;*/
        /*color:#000;*/
        /*margin: 0;*/``
        /*padding: 0;*/
    /*}*/
    .swiper-container {
        width: 100%;
        height: 300px;
        margin-left: auto;
        margin-right: auto;
    }
    .swiper-slide {
        background-size: cover;
        background-position: center;
    }
    .gallery-top {
        height: 80%;
        width: 100%;
    }
    .gallery-thumbs {
        height: 20%;
        box-sizing: border-box;
        padding: 10px 0;
    }
    .gallery-thumbs .swiper-slide {
        height: 100%;
        opacity: 0.4;
    }
    .gallery-thumbs .swiper-slide-thumb-active {
        opacity: 1;
    }

</style>
<div class="swiper-container gallery-top">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/1/" ></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/2/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/3/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/4/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/5/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/6/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/7/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/8/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/9/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/10/"></div>
    </div>
    <!-- Add Arrows -->
    <div class="swiper-button-next swiper-button-white"></div>
    <div class="swiper-button-prev swiper-button-white"></div>
</div>
<div class="swiper-container gallery-thumbs">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/1/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/2/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/3/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/4/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/5/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/6/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/7/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/8/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/9/"></div>
        <div class="swiper-slide"><img src="http://lorempixel.com/1200/1200/nature/10/"></div>
    </div>
</div>
<script>
    require(['jquery','swiper'], function($, Swiper) {
        var galleryThumbs = new Swiper('.gallery-thumbs', {
            spaceBetween: 10,
            slidesPerView: 4,
            loop: true,
            freeMode: true,
            loopedSlides: 5, //looped slides should be the same
            watchSlidesVisibility: true,
            watchSlidesProgress: true,
        });
        var galleryTop = new Swiper('.gallery-top', {
            spaceBetween: 10,
            loop: true,
            loopedSlides: 5, //looped slides should be the same
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            thumbs: {
                swiper: galleryThumbs,
            },
        });
    });
</script>